// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgBIDOlhqEXXpMMCfJYgGMnDsHH30pT9s',
    appId: '1:220078960600:web:275d5e0bca3ac1e9630cad',
    messagingSenderId: '220078960600',
    projectId: 'note-app-firebase-fb015',
    authDomain: 'note-app-firebase-fb015.firebaseapp.com',
    storageBucket: 'note-app-firebase-fb015.firebasestorage.app',
    measurementId: 'G-R3103CE71N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2p8GGRfXMdAQ3WQS2DS4PaYK-NrEByM',
    appId: '1:220078960600:android:1837dd117bc7097d630cad',
    messagingSenderId: '220078960600',
    projectId: 'note-app-firebase-fb015',
    storageBucket: 'note-app-firebase-fb015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS1WD3LuHHp26aVSlAIY3XErBGzvd40Wk',
    appId: '1:220078960600:ios:61342bdb270ebf39630cad',
    messagingSenderId: '220078960600',
    projectId: 'note-app-firebase-fb015',
    storageBucket: 'note-app-firebase-fb015.firebasestorage.app',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS1WD3LuHHp26aVSlAIY3XErBGzvd40Wk',
    appId: '1:220078960600:ios:61342bdb270ebf39630cad',
    messagingSenderId: '220078960600',
    projectId: 'note-app-firebase-fb015',
    storageBucket: 'note-app-firebase-fb015.firebasestorage.app',
    iosBundleId: 'com.example.notesAppFirebase',
  );
}
